
---
- name: Mettre à jour les serveurs
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      apt:
        upgrade: dist

    - name: Mettre à jour uniquement les paquets de sécurité
      apt:
        upgrade: yes
