---
- name: Configurer les serveurs web
  hosts: webservers
  become: yes
  tasks:
    - name: Installer un serveur HTTP
      apt:
        name: apache2
        state: present

- name: Configurer les serveurs de bases de données
  hosts: dbservers
  become: yes
  tasks:
    - name: Installer MySQL
      apt:
        name: mysql-server
        state: present
